In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [2]:
sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = [1, 0, 0, 1, 1, 0, 1]

In [3]:
t=Tokenizer()
t.fit_on_texts(sentences)
vocab_size = len(t.word_index)+1
print(vocab_size)

16


In [4]:
X_encoded=t.texts_to_sequences(sentences)
print(X_encoded)

[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]


In [5]:
max_len=max(len(l) for l in X_encoded)
print(max_len)

4


In [6]:
x_train=pad_sequences(X_encoded,maxlen=max_len,padding='post')
y_train=np.array(y_train)
print(x_train)

[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]


In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

model=Sequential()
model.add(Embedding(vocab_size,4,input_length=max_len))

model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [10]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
model.fit(x_train,y_train,epochs=100,verbose=2)


Epoch 1/100
1/1 - 1s - loss: 0.6928 - acc: 0.4286
Epoch 2/100
1/1 - 0s - loss: 0.6918 - acc: 0.4286
Epoch 3/100
1/1 - 0s - loss: 0.6908 - acc: 0.4286
Epoch 4/100
1/1 - 0s - loss: 0.6898 - acc: 0.4286
Epoch 5/100
1/1 - 0s - loss: 0.6887 - acc: 0.5714
Epoch 6/100
1/1 - 0s - loss: 0.6877 - acc: 0.5714
Epoch 7/100
1/1 - 0s - loss: 0.6867 - acc: 0.5714
Epoch 8/100
1/1 - 0s - loss: 0.6857 - acc: 0.5714
Epoch 9/100
1/1 - 0s - loss: 0.6846 - acc: 0.5714
Epoch 10/100
1/1 - 0s - loss: 0.6836 - acc: 0.5714
Epoch 11/100
1/1 - 0s - loss: 0.6826 - acc: 0.5714
Epoch 12/100
1/1 - 0s - loss: 0.6815 - acc: 0.5714
Epoch 13/100
1/1 - 0s - loss: 0.6805 - acc: 0.5714
Epoch 14/100
1/1 - 0s - loss: 0.6794 - acc: 0.5714
Epoch 15/100
1/1 - 0s - loss: 0.6784 - acc: 0.5714
Epoch 16/100
1/1 - 0s - loss: 0.6773 - acc: 0.5714
Epoch 17/100
1/1 - 0s - loss: 0.6762 - acc: 0.5714
Epoch 18/100
1/1 - 0s - loss: 0.6752 - acc: 0.5714
Epoch 19/100
1/1 - 0s - loss: 0.6741 - acc: 0.5714
Epoch 20/100
1/1 - 0s - loss: 0.6730 - a

In [11]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove*.zip

'wget'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
'unzip'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
